version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Clone git submodules
          command: |
            cd ~/repo
            git submodule update --init
