# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            bash .circleci/deps.sh

      - run:
          name: create venv
          command: |
            bash .circleci/create_venv.sh

      - run:
          name: install miniconda
          command: |
            bash .circleci/install_miniconda.sh

      - run:
          name: create conda env
          command: |
            bash .circleci/create_conda_env.sh

      - run:
          name: pip install
          command: |
            bash .circleci/pip_install.sh

      - run:
          name: run test
          command: |
            bash .circleci/test.sh
